name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build

      #发布到Basilosauridae.github.io/main
      - name: Deploy Basilosauridae.github.io/main
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          EXTERNAL_REPOSITORY: Basilosauridaes/Basilosauridae.github.io #可以新建一个Basilosauridae.github.io仓库发布到main
          PUBLISH_BRANCH: main
          PUBLISH_DIR: .vuepress/dist
        with:
          emptyCommits: false
